### ISSUE TITLE
Parent Child Relationship in Mailing List

### ISSUE THREAD

**Issue by st252099074** [sailuh/perceive#65]
For the threads with replies in Full Disclosure which of the following is desired:

1) Depicting parent-child relationships as the structure "model" does. We will be able to tell the starters and their following replies within the common topics.

2) We only want to group the Emails in respect of their topics regardless which Emails started the conversation and which Emails are the replies.

**Comment by carlosparadis** [comment]
Hi @st252099074 I would prefer we stick to the same issue thread when addressing the same problem to avoid duplicates. Please use #57 for this discussion.
